#!/usr/bin/env bash
# script that transfers a file to a remote server
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictMostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
